#!/usr/bin/env node
import { Command } from 'commander';
import { parsePrUrl } from './parser';
import { fetchPrDiff } from './github';
import { runReviewAgent } from './agent';

const program = new Command();

program
  .name('claude-review')
  .description('Claude Code sub-agent that reviews a GitHub PR and outputs structured Markdown')
  .version('1.0.0')
  .requiredOption('--pr <url>', 'GitHub PR URL (e.g. https://github.com/owner/repo/pull/123)')
  .option('--output <file>', 'Write review to a file instead of stdout')
  .action(async (options) => {
    const githubToken = process.env.GITHUB_TOKEN;
    const anthropicKey = process.env.ANTHROPIC_API_KEY;

    if (!githubToken) {
      console.error('Error: GITHUB_TOKEN environment variable is required');
      process.exit(1);
    }
    if (!anthropicKey) {
      console.error('Error: ANTHROPIC_API_KEY environment variable is required');
      process.exit(1);
    }

    try {
      const pr = parsePrUrl(options.pr);
      console.error(`Fetching diff for ${pr.owner}/${pr.repo}#${pr.pull_number}...`);

      const diff = await fetchPrDiff(pr, githubToken);
      console.error(`Diff fetched (${diff.length} bytes). Running Claude review...`);

      const review = await runReviewAgent(diff, anthropicKey);

      const header = `# PR Review: ${options.pr}\n\n_Generated by claude-review agent_\n\n---\n\n`;
      const output = header + review;

      if (options.output) {
        const { writeFileSync } = await import('fs');
        writeFileSync(options.output, output, 'utf-8');
        console.error(`Review written to ${options.output}`);
      } else {
        console.log(output);
      }
    } catch (err: unknown) {
      console.error('Error:', err instanceof Error ? err.message : String(err));
      process.exit(1);
    }
  });

program.parse();